// --- Level Functions ---
function isWall(gridX, gridY) { if (gridX < 0 || gridX >= level.width || gridY < 0 || gridY >= level.height) return true; const tileType = level.grid?.[gridY]?.[gridX]; return tileType === TILE.WALL || tileType === TILE.OBSTACLE; }
function isSolidForPlayer(gridX, gridY) { if (gridX < 0 || gridX >= level.width || gridY < 0 || gridY >= level.height) return true; const tileType = level.grid?.[gridY]?.[gridX]; return tileType === TILE.WALL || tileType === TILE.OBSTACLE || tileType === TILE.ENTRANCE; }
function checkWallCollision(px, py, r) { const margin = 0.1; const checkPoints = [ { x: px, y: py }, { x: px + r - margin, y: py }, { x: px - r + margin, y: py }, { x: px, y: py + r - margin }, { x: px, y: py - r + margin }, { x: px + (r - margin) * 0.707, y: py + (r - margin) * 0.707 }, { x: px - (r - margin) * 0.707, y: py + (r - margin) * 0.707 }, { x: px + (r - margin) * 0.707, y: py - (r - margin) * 0.707 }, { x: px - (r - margin) * 0.707, y: py - (r - margin) * 0.707 } ]; for (const p of checkPoints) { const gridX = Math.floor(p.x / TILE_SIZE); const gridY = Math.floor(p.y / TILE_SIZE); if (isSolidForPlayer(gridX, gridY)) return true; } return false; }
function generateLevel(levelData, widthTiles, heightTiles) { levelData.width = widthTiles; levelData.height = heightTiles; levelData.grid = Array.from({ length: heightTiles }, () => Array(widthTiles).fill(TILE.WALL)); levelData.fogGrid = Array.from({ length: heightTiles }, () => Array(widthTiles).fill(FOG_STATE.HIDDEN));
    levelData.entrances = []; const totalTiles = widthTiles * heightTiles; const stack = []; let startX = 1; let startY = Math.max(1, Math.floor(heightTiles / 2) - 1); if (startY % 2 === 0) startY--; levelData.grid[startY][startX] = TILE.FLOOR; stack.push({ x: startX, y: startY }); levelData.startX = startX * TILE_SIZE + TILE_SIZE / 2; levelData.startY = startY * TILE_SIZE + TILE_SIZE / 2; const carve = (x, y) => { if (x > 0 && x < widthTiles - 1 && y > 0 && y < heightTiles - 1) levelData.grid[y][x] = TILE.FLOOR; }; let mazeGenSteps = 0; const maxMazeGenSteps = widthTiles * heightTiles * 2; while (stack.length > 0 && mazeGenSteps < maxMazeGenSteps) { mazeGenSteps++; const current = stack[stack.length - 1]; const neighbors = []; const directions = [{ x: 0, y: -2 }, { x: 0, y: 2 }, { x: -2, y: 0 }, { x: 2, y: 0 }]; directions.sort(() => Math.random() - 0.5); for (const dir of directions) { const nx = current.x + dir.x; const ny = current.y + dir.y; if (nx > 0 && nx < widthTiles - 1 && ny > 0 && ny < heightTiles - 1 && levelData.grid[ny]?.[nx] === TILE.WALL) { neighbors.push({ x: nx, y: ny, wallX: current.x + dir.x / 2, wallY: current.y + dir.y / 2 }); } } if (neighbors.length > 0) { const chosen = neighbors[0]; carve(chosen.wallX, chosen.wallY); carve(chosen.x, chosen.y); stack.push({ x: chosen.x, y: chosen.y }); } else { stack.pop(); } } if (mazeGenSteps >= maxMazeGenSteps) console.warn("Maze gen steps exceeded.");
    const startGridX = startX; const startGridY = startY; for (let dy = -START_AREA_RADIUS; dy <= START_AREA_RADIUS; dy++) { for (let dx = -START_AREA_RADIUS; dx <= START_AREA_RADIUS; dx++) { const gridX = startGridX + dx; const gridY = startGridY + dy; if (gridX > 0 && gridX < widthTiles - 1 && gridY > 0 && gridY < heightTiles - 1) { levelData.grid[gridY][gridX] = TILE.FLOOR; levelData.fogGrid[gridY][gridX] = FOG_STATE.REVEALED; } } } const obstaclesToPlace = Math.floor(totalTiles / OBSTACLE_DENSITY_FACTOR);
    for (let i = 0; i < obstaclesToPlace; i++) { const sizeW = getRandomInt(OBSTACLE_MIN_SIZE, OBSTACLE_MAX_SIZE); const sizeH = getRandomInt(OBSTACLE_MIN_SIZE, OBSTACLE_MAX_SIZE); const randX = getRandomInt(1, widthTiles - sizeW - 1); const randY = getRandomInt(1, heightTiles - sizeH - 1); for (let y = randY; y < randY + sizeH; y++) { for (let x = randX; x < randX + sizeW; x++) { if (x > 0 && x < widthTiles - 1 && y > 0 && y < heightTiles - 1) levelData.grid[y][x] = TILE.OBSTACLE; } } }
    let loopsCreated = 0; for (let y = 1; y < heightTiles - 1; y++) { for (let x = 1; x < widthTiles - 1; x++) { if (levelData.grid[y][x] === TILE.WALL || levelData.grid[y][x] === TILE.OBSTACLE) { if (x > 0 && x < widthTiles - 1 && levelData.grid[y]?.[x - 1] === TILE.FLOOR && levelData.grid[y]?.[x + 1] === TILE.FLOOR && Math.random() < LOOP_CREATION_PROBABILITY) { levelData.grid[y][x] = TILE.FLOOR; loopsCreated++; continue; } if (y > 0 && y < heightTiles - 1 && levelData.grid[y - 1]?.[x] === TILE.FLOOR && levelData.grid[y + 1]?.[x] === TILE.FLOOR && Math.random() < LOOP_CREATION_PROBABILITY) { levelData.grid[y][x] = TILE.FLOOR; loopsCreated++; } } } }
    const openingsToCarve = Math.floor(totalTiles / CARVING_DENSITY_FACTOR);
    for (let i = 0; i < openingsToCarve; i++) { const size = getRandomInt(CARVING_MIN_SIZE, CARVING_MAX_SIZE); const randX = getRandomInt(1, widthTiles - size - 1); const randY = getRandomInt(1, heightTiles - size - 1); for (let y = randY; y < randY + size; y++) { for (let x = randX; x < randX + size; x++) { if (x > 0 && x < widthTiles - 1 && y > 0 && y < heightTiles - 1) levelData.grid[y][x] = TILE.FLOOR; } } }
    const numSections = 7; const sectionWidth = Math.floor(widthTiles / numSections); const blockCarveDensitiesRandom = [...BLOCK_CARVE_DENSITIES].sort(() => Math.random() - 0.5); let blockCarvingsDone = 0; for (let section = 0; section < numSections; section++) { const blockStartX = section * sectionWidth; const blockEndX = (section === numSections - 1) ? widthTiles : blockStartX + sectionWidth; const blockStartY = 0; const blockEndY = heightTiles; const blockArea = (blockEndX - blockStartX) * (blockEndY - blockStartY); const currentBlockCarveDensity = blockCarveDensitiesRandom[section % blockCarveDensitiesRandom.length]; const carvingsInBlock = Math.max(1, Math.floor(blockArea / currentBlockCarveDensity));
    for(let i = 0; i < carvingsInBlock; i++) { const size = getRandomInt(BLOCK_CARVE_MIN_SIZE, BLOCK_CARVE_MAX_SIZE); const randX = getRandomInt(Math.max(1, blockStartX), Math.min(widthTiles - size - 1, blockEndX - size -1)); const randY = getRandomInt(Math.max(1, blockStartY), Math.min(heightTiles - size - 1, blockEndY - size -1)); for (let y = randY; y < randY + size; y++) { for (let x = randX; x < randX + size; x++) { if (x > 0 && x < widthTiles - 1 && y > 0 && y < heightTiles - 1) { levelData.grid[y][x] = TILE.FLOOR; } } } blockCarvingsDone++; } }
    let maxDist = -1; let endTileX = -1; let endTileY = -1; const searchStartX = Math.floor(widthTiles * (2 / 3)); for (let y = 1; y < heightTiles - 1; y++) { for (let x = widthTiles - 2; x >= searchStartX; x--) { if (levelData.grid[y]?.[x] === TILE.FLOOR) { const dx = x - startX; if (dx > maxDist) { maxDist = dx; endTileX = x; endTileY = y; } } } } if (endTileX === -1) { maxDist = -1; for (let y = 1; y < heightTiles - 1; y++) { for (let x = 1; x < widthTiles - 1; x++) { if (levelData.grid[y]?.[x] === TILE.FLOOR) { const d = distance(startX, startY, x, y); if (d > maxDist) { maxDist = d; endTileX = x; endTileY = y; } } } } } if (endTileX === -1) { console.error("No end point found!"); endTileX = widthTiles - 2; endTileY = 1; if (levelData.grid[endTileY]?.[endTileX] !== undefined) levelData.grid[endTileY][endTileX] = TILE.FLOOR; } levelData.endX = endTileX * TILE_SIZE + TILE_SIZE / 2; levelData.endY = endTileY * TILE_SIZE + TILE_SIZE / 2;
    const minEntranceExitDistTiles = levelData.width * MIN_ENTRANCE_EXIT_DISTANCE_FACTOR;
    const minEntranceExitDistSq = (minEntranceExitDistTiles * TILE_SIZE) ** 2;
    const entranceCandidates = []; for (let x = 1; x < widthTiles - 1; x++) entranceCandidates.push({ x: x, y: 0, edge: 'top' }); for (let x = 1; x < widthTiles - 1; x++) entranceCandidates.push({ x: x, y: heightTiles - 1, edge: 'bottom' }); for (let y = 1; y < heightTiles - 1; y++) entranceCandidates.push({ x: 0, y: y, edge: 'left' }); for (let y = 1; y < heightTiles - 1; y++) entranceCandidates.push({ x: widthTiles - 1, y: y, edge: 'right' }); entranceCandidates.sort(() => Math.random() - 0.5); let entrancesCreated = 0; const minEntranceSeparation = Math.max(3, Math.floor(widthTiles / (NUM_ENTRANCES_PER_SIDE * 2))); const placedEntrances = { top: [], bottom: [], left: [], right: []}; for (const cand of entranceCandidates) { let insideX = cand.x, insideY = cand.y; if (cand.edge === 'top') insideY++; else if (cand.edge === 'bottom') insideY--; else if (cand.edge === 'left') insideX++; else if (cand.edge === 'right') insideX--; if (insideX > 0 && insideX < widthTiles - 1 && insideY > 0 && insideY < heightTiles - 1 && levelData.grid[insideY]?.[insideX] === TILE.FLOOR) { const distToExitSq = (cand.x * TILE_SIZE - levelData.endX)**2 + (cand.y * TILE_SIZE - levelData.endY)**2; if (distToExitSq < minEntranceExitDistSq) { continue; } let tooClose = false; const edgeList = placedEntrances[cand.edge]; for(const existing of edgeList) { const separation = (cand.edge === 'top' || cand.edge === 'bottom') ? Math.abs(cand.x - existing.x) : Math.abs(cand.y - existing.y); if (separation < minEntranceSeparation) { tooClose = true; break; } } if (tooClose) continue; levelData.grid[cand.y][cand.x] = TILE.ENTRANCE; const entranceCoord = { x: cand.x, y: cand.y }; levelData.entrances.push(entranceCoord); edgeList.push(entranceCoord); entrancesCreated++; if (entrancesCreated >= NUM_ENTRANCES_PER_SIDE * 4) break; } } console.log(`Entrances placed: ${levelData.entrances.length}`);
    levelData.pathfinderGrid = new PF.Grid(widthTiles, heightTiles); for (let y = 0; y < heightTiles; y++) { for (let x = 0; x < widthTiles; x++) { const tileType = levelData.grid[y]?.[x]; const isWalkable = tileType === TILE.FLOOR || tileType === TILE.ENTRANCE; levelData.pathfinderGrid.setWalkableAt(x, y, isWalkable); } } }

function drawLevel(ctx, levelData, offsetX, offsetY) { const startCol = Math.max(0, Math.floor(offsetX / TILE_SIZE)); const endCol = Math.min(levelData.width, Math.ceil((offsetX + canvas.width) / TILE_SIZE)); const startRow = Math.max(0, Math.floor(offsetY / TILE_SIZE)); const endRow = Math.min(levelData.height, Math.ceil((offsetY + canvas.height) / TILE_SIZE)); ctx.lineWidth = 1; for (let y = startRow; y < endRow; y++) { if (!levelData.grid[y]) continue; for (let x = startCol; x < endCol; x++) { const screenX = x * TILE_SIZE - offsetX; const screenY = y * TILE_SIZE - offsetY; const tileType = levelData.grid[y][x]; let fillColor = COLOR_FLOOR; let stroke = false; switch (tileType) { case TILE.WALL: fillColor = COLOR_WALL; stroke = true; break; case TILE.OBSTACLE: fillColor = COLOR_OBSTACLE; stroke = true; break; case TILE.ENTRANCE: fillColor = COLOR_ENTRANCE; break; default: fillColor = COLOR_FLOOR; break; } ctx.fillStyle = fillColor; ctx.fillRect(screenX, screenY, TILE_SIZE, TILE_SIZE); if (stroke) { ctx.strokeStyle = COLOR_WALL_STROKE; ctx.strokeRect(screenX, screenY, TILE_SIZE, TILE_SIZE); } } }
    ctx.fillStyle = FOG_COLOR_HIDDEN; for (let y = startRow; y < endRow; y++) { if (!levelData.fogGrid[y]) continue; for (let x = startCol; x < endCol; x++) { if (levelData.fogGrid[y][x] === FOG_STATE.HIDDEN) { const screenX = x * TILE_SIZE - offsetX; const screenY = y * TILE_SIZE - offsetY; ctx.fillRect(screenX, screenY, TILE_SIZE + 1, TILE_SIZE + 1); } } }
    if (levelData.endX > 0 && levelData.endY > 0) { const endGridX = Math.floor(levelData.endX / TILE_SIZE); const endGridY = Math.floor(levelData.endY / TILE_SIZE); if (levelData.fogGrid?.[endGridY]?.[endGridX] === FOG_STATE.REVEALED) { ctx.fillStyle = 'rgba(0, 255, 0, 0.3)'; ctx.fillRect(levelData.endX - TILE_SIZE / 2 - offsetX, levelData.endY - TILE_SIZE / 2 - offsetY, TILE_SIZE, TILE_SIZE); ctx.strokeStyle = 'lime'; ctx.lineWidth = 2; ctx.strokeRect(levelData.endX - TILE_SIZE / 2 - offsetX, levelData.endY - TILE_SIZE / 2 - offsetY, TILE_SIZE, TILE_SIZE); } } }

function updateFogOfWar() {
    if (!player || !level.fogGrid) return;

    const revealTile = (gridX, gridY) => {
         if (gridX >= 0 && gridX < level.width && gridY >= 0 && gridY < level.height) {
             level.fogGrid[gridY][gridX] = FOG_STATE.REVEALED;
         }
    };

    const revealAround = (centerX, centerY, radiusInTiles) => {
        if (!centerX || !centerY || !radiusInTiles) return;
        const centerGridX = Math.floor(centerX / TILE_SIZE);
        const centerGridY = Math.floor(centerY / TILE_SIZE);
        const radiusSq = radiusInTiles * radiusInTiles;

        for (let dy = -radiusInTiles; dy <= radiusInTiles; dy++) {
            for (let dx = -radiusInTiles; dx <= radiusInTiles; dx++) {
                if (dx*dx + dy*dy <= radiusSq) {
                    const gridX = centerGridX + dx;
                    const gridY = centerGridY + dy;
                    if (gridX >= 0 && gridX < level.width && gridY >= 0 && gridY < level.height) {
                        const tileCenterX = gridX * TILE_SIZE + TILE_SIZE / 2;
                        const tileCenterY = gridY * TILE_SIZE + TILE_SIZE / 2;
                        if (hasLineOfSight(centerX, centerY, tileCenterX, tileCenterY, isWall, revealTile, FOG_LOS_STEP_SCALE)) {
                           revealTile(gridX, gridY);
                        }
                    }
                }
            }
        }
    };

    revealAround(player.x, player.y, PLAYER_VISION_RADIUS);
    mercenaries.forEach(merc => { if (merc.active) { revealAround(merc.x, merc.y, MERC_VISION_RADIUS); } });
    player.drones.forEach(drone => {
        revealAround(drone.x, drone.y, DRONE_VISION_RADIUS);
    });
}

// --- Helper function to destroy a tile ---
function destroyTile(gridX, gridY) { if (gridX > 0 && gridX < level.width - 1 && gridY > 0 && gridY < level.height - 1) { const tileType = level.grid[gridY]?.[gridX]; if (tileType === TILE.WALL || tileType === TILE.OBSTACLE) { level.grid[gridY][gridX] = TILE.FLOOR; if (level.pathfinderGrid) { level.pathfinderGrid.setWalkableAt(gridX, gridY, true); } if (level.fogGrid?.[gridY]?.[gridX] !== undefined) { level.fogGrid[gridY][gridX] = FOG_STATE.REVEALED; } } } }